spring:
  application:
    name: eureka_client_killer
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ping-server:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
